stages:
  - test

robot_test:
  image: python:3.8-slim
  stage: test
  script:
    - pip install robotframework
    - pip install selenium
    - pip install robotframework-seleniumlibrary
    - git clone https://github.com/Ahmed-inovat8/Edit_Functionality_Changes_Complete.git
    - cd Inovat8-Project-database-main
    - robot SF_US1.robot
  artifacts:
    paths:
      - output.xml
      - report.html
      - log.html
  only:
    - main
